export { default as Aboutus } from './Aboutus/Aboutus.jsx'
export { default as Chef } from './Chef/Chef.jsx'
export { default as Findus } from './Findus/Findus.jsx'
export { default as Footer } from './Footer/Footer.jsx'
export { default as Gallery } from './Gallery/Gallery.jsx'
export { default as Header } from './Header/Header.jsx'
export { default as Intro } from './Intro/Intro.jsx'
export { default as Laures } from './Laures/Laures.jsx'
export { default as Menu } from './Menu/Menu.jsx'

